WITH FEATURES AS (
    {}
    -- Replace {} with the actual part of the query or data that populates the FEATURES CTE.
    -- Example:
    -- SELECT :ID AS ID FROM dual
), FEATURE_HIERARCHY (ID, FEATURE_ID, VAL_LOD, VAL_IMPLICITGEOM_ID, VAL_FEATURE_ID, VAL_RELATION_TYPE)
AS (
    -- Initial anchor member
    SELECT 
        NULL AS ID,
        F.ID AS FEATURE_ID,
        NULL AS VAL_LOD,
        NULL AS VAL_IMPLICITGEOM_ID,
        F.ID AS VAL_FEATURE_ID,
        1 AS VAL_RELATION_TYPE
    FROM @SCHEMA@.FEATURE F
    INNER JOIN FEATURES Q ON Q.ID = F.ID

    UNION ALL

    -- Recursive member
    SELECT 
        P.ID,
        P.FEATURE_ID,
        P.VAL_LOD,
        P.VAL_IMPLICITGEOM_ID,
        P.VAL_FEATURE_ID,
        P.VAL_RELATION_TYPE
    FROM @SCHEMA@.PROPERTY P
    INNER JOIN FEATURE_HIERARCHY H 
        ON H.VAL_FEATURE_ID = P.FEATURE_ID 
        AND H.VAL_RELATION_TYPE = 1
)
CYCLE ID SET IS_CYCLE to TRUE DEFAULT FALSE
SELECT DISTINCT
    H.VAL_IMPLICITGEOM_ID AS ID,
    H.VAL_LOD AS LOD
FROM FEATURE_HIERARCHY H
WHERE H.VAL_IMPLICITGEOM_ID IS NOT NULL
      AND NOT IS_CYCLE;

