WITH RECURSIVE FEATURES AS (
	%FEATURE_QUERY%
), FEATURE_HIERARCHY AS
  (SELECT NULL::bigint AS ID,
     F.ID AS FEATURE_ID,
     NULL::text AS VAL_LOD,
     NULL::bigint AS VAL_IMPLICITGEOM_ID,
     F.ID AS VAL_FEATURE_ID,
     NULL::int AS VAL_REFERENCE_TYPE,   
     FALSE AS IS_CYCLE,
     ARRAY[]::bigint[] AS PATH
   FROM %SCHEMA%.FEATURE F
   INNER JOIN FEATURES Q on Q.ID = F.ID
   UNION ALL SELECT
     P.ID,
     P.FEATURE_ID,
     P.VAL_LOD,
     P.VAL_IMPLICITGEOM_ID,
     P.VAL_FEATURE_ID,
     P.VAL_REFERENCE_TYPE,   
     P.ID = ANY(PATH),
     PATH || P.ID
   FROM %SCHEMA%.PROPERTY P
   INNER JOIN FEATURE_HIERARCHY H ON H.VAL_FEATURE_ID = P.FEATURE_ID AND H.VAL_REFERENCE_TYPE IS NULL)
SELECT DISTINCT
  H.VAL_IMPLICITGEOM_ID AS ID,
  H.VAL_LOD AS LOD
FROM FEATURE_HIERARCHY H
WHERE H.VAL_IMPLICITGEOM_ID IS NOT null AND NOT IS_CYCLE