WITH RECURSIVE FEATURES AS (
  {}
),
FEATURE_HIERARCHY AS (
  SELECT
    F.ID AS FEATURE_ID
  FROM @SCHEMA@.FEATURE F
  INNER JOIN FEATURES Q ON Q.ID = F.ID
  UNION
  SELECT
    P.VAL_FEATURE_ID
  FROM @SCHEMA@.PROPERTY P
  INNER JOIN FEATURE_HIERARCHY H ON H.FEATURE_ID = P.FEATURE_ID
  WHERE
    P.VAL_FEATURE_ID IS NOT NULL
    AND P.VAL_RELATION_TYPE = 1
)
SELECT DISTINCT
  P.VAL_IMPLICITGEOM_ID AS ID,
  P.VAL_LOD AS LOD
FROM @SCHEMA@.PROPERTY P
INNER JOIN FEATURE_HIERARCHY H ON H.FEATURE_ID = P.FEATURE_ID
WHERE P.VAL_IMPLICITGEOM_ID IS NOT NULL